$(OBJDIR)/alloc.o: src/alloc.c src/alloc.h src/error.h
$(OBJDIR)/bindings.o: src/bindings.c src/bindings.h src/mylua.h src/extdata.h \
 src/store/store.h src/object.h src/objtypes.h src/bindings.inc
$(OBJDIR)/bitmask.o: src/bitmask.c src/bitmask.h
$(OBJDIR)/bitmaskg.o: src/bitmaskg.c src/bitmask.h src/bitmaskg.h \
 src/store/store.h
$(OBJDIR)/bitmaskr.o: src/bitmaskr.c src/alloc.h src/bitmask.h src/bitmaskr.h \
 src/list.h
$(OBJDIR)/camera.o: src/camera.c src/alloc.h src/camera.h \
 src/fastsqrt/fastsqrt.h src/object.h src/mylua.h
$(OBJDIR)/error.o: src/error.c src/error.h
$(OBJDIR)/extdata.o: src/extdata.c src/bitmaskg.h src/extdata.h \
 src/magic/magic4x4.h
$(OBJDIR)/fps.o: src/fps.c src/fps.h
$(OBJDIR)/gameclt.o: src/gameclt.c src/camera.h src/error.h src/fps.h \
 src/gameclt.h src/list.h src/magic/magic4x4.h src/magic/magicrt.h \
 src/map.h src/mapfile.h src/netmsg.h src/object.h src/mylua.h \
 src/packet.h src/physics.h src/render.h src/store/store.h \
 src/timeout.h src/yield.h
$(OBJDIR)/gameinit.o: src/gameinit.c src/bindings.h src/bitmaskr.h \
 src/fastsqrt/fastsqrt.h src/gameinit.h src/jpgalleg/jpgalleg.h \
 src/loaddata.h src/magic/magic4x4.h src/mylua.h src/object.h \
 src/objtypes.h src/path.h src/store/store.h
$(OBJDIR)/gamesrv.o: src/gamesrv.c src/alloc.h src/error.h src/gamesrv.h \
 src/list.h src/map.h src/mapfile.h src/netmsg.h src/object.h \
 src/mylua.h src/objtypes.h src/packet.h src/physics.h src/timeout.h \
 src/yield.h
$(OBJDIR)/loaddata.o: src/loaddata.c src/alloc.h src/extdata.h src/loaddata.h \
 src/path.h src/store/store.h src/vtree.h
$(OBJDIR)/main.o: src/main.c src/editor/editor.h src/gameinit.h src/gameclt.h \
 src/gamesrv.h src/textface.h
$(OBJDIR)/map.o: src/map.c src/alloc.h src/bitmask.h src/list.h src/map.h \
 src/object.h src/mylua.h src/store/store.h
$(OBJDIR)/mapfile.o: src/mapfile.c src/list.h src/map.h src/mapfile.h \
 src/object.h src/mylua.h src/objtypes.h src/store/store.h
$(OBJDIR)/mylua.o: src/mylua.c src/mylua.h src/path.h
$(OBJDIR)/object.o: src/object.c src/alloc.h src/bitmask.h src/bitmaskg.h \
 src/bitmaskr.h src/list.h src/magic/magic4x4.h src/map.h src/mylua.h \
 src/object.h src/objtypes.h src/store/store.h src/objecttm.inc
$(OBJDIR)/objtypes.o: src/objtypes.c src/alloc.h src/bitmask.h src/bitmaskg.h \
 src/mylua.h src/objtypes.h src/store/store.h
$(OBJDIR)/packet.o: src/packet.c src/packet.h src/error.h
$(OBJDIR)/path.o: src/path.c src/path.h
$(OBJDIR)/physics.o: src/physics.c src/alloc.h src/map.h src/object.h \
 src/mylua.h src/physics.h
$(OBJDIR)/render.o: src/render.c src/camera.h src/list.h src/magic/magic4x4.h \
 src/map.h src/object.h src/mylua.h src/store/store.h src/render.h
$(OBJDIR)/textface.o: src/textface.c src/gamesrv.h src/textface.h
$(OBJDIR)/timeout.o: src/timeout.c src/alloc.h src/timeout.h
$(OBJDIR)/yield.o: src/yield.c src/yield.h
$(OBJDIR)/example.o: src/store/example.c src/store/store.h
$(OBJDIR)/hash.o: src/store/hash.c src/store/hash.h
$(OBJDIR)/store.o: src/store/store.c src/store/hash.h src/store/store.h
$(OBJDIR)/magic4x4.o: src/magic/magic4x4.c src/magic/magic4x4.h
$(OBJDIR)/magicrot.o: src/magic/magicrot.c src/magic/magic4x4.h
$(OBJDIR)/magicrt.o: src/magic/magicrt.c src/magic/magicrt.h
$(OBJDIR)/bmark.o: src/fastsqrt/bmark.c src/fastsqrt/fastsqrt.h
$(OBJDIR)/fastsqrt.o: src/fastsqrt/fastsqrt.c src/fastsqrt/fastsqrt.h
$(OBJDIR)/jpeg.o: src/jpgalleg/jpeg.c
$(OBJDIR)/gui.o: src/gui/gui.c src/gui/gui.h src/gui/guiinter.h src/yield.h
$(OBJDIR)/guiaccel.o: src/gui/guiaccel.c src/gui/gui.h src/gui/guiinter.h
$(OBJDIR)/guidirty.o: src/gui/guidirty.c src/gui/gui.h src/gui/guiinter.h
$(OBJDIR)/guimouse.o: src/gui/guimouse.c src/gui/gui.h src/gui/guiinter.h
$(OBJDIR)/guiwm.o: src/gui/guiwm.c src/gui/gui.h src/gui/guiinter.h
$(OBJDIR)/guiwmdef.o: src/gui/guiwmdef.c src/gui/gui.h src/gui/guiinter.h
$(OBJDIR)/ug.o: src/ug/ug.c src/ug/ug.h src/ug/ugtheme.h
$(OBJDIR)/ugblank.o: src/ug/ugblank.c src/ug/ug.h src/ug/uginter.h
$(OBJDIR)/ugbutton.o: src/ug/ugbutton.c src/ug/ug.h src/ug/uginter.h \
 src/ug/ugtheme.h
$(OBJDIR)/ugdialog.o: src/ug/ugdialog.c src/gui/gui.h src/ug/ug.h \
 src/ug/uginter.h src/ug/ugtheme.h
$(OBJDIR)/ugevent.o: src/ug/ugevent.c src/ug/ug.h src/ug/uginter.h
$(OBJDIR)/uglayout.o: src/ug/uglayout.c src/ug/ug.h
$(OBJDIR)/ugmenu.o: src/ug/ugmenu.c src/gui/gui.h src/ug/ug.h src/ug/uginter.h \
 src/ug/ugtheme.h
$(OBJDIR)/ugscroll.o: src/ug/ugscroll.c
$(OBJDIR)/ugtheme.o: src/ug/ugtheme.c src/ug/ugtheme.h
$(OBJDIR)/ugthmmot.o: src/ug/ugthmmot.c src/ug/ugtheme.h
$(OBJDIR)/ugthmpaw.o: src/ug/ugthmpaw.c src/ug/ugtheme.h
$(OBJDIR)/ugwidget.o: src/ug/ugwidget.c src/ug/ug.h src/ug/uginter.h
$(OBJDIR)/cursor.o: src/editor/cursor.c src/editor/cursor.h src/magic/magic4x4.h
$(OBJDIR)/editarea.o: src/editor/editarea.c src/gui/gui.h src/alloc.h \
 src/editor/editarea.h src/list.h src/magic/magic4x4.h \
 src/editor/modes.h src/editor/selbar.h
$(OBJDIR)/editor.o: src/editor/editor.c src/gui/gui.h src/ug/ug.h \
 src/editor/cursor.h src/store/store.h src/path.h src/vtree.h \
 src/editor/editarea.h src/editor/menu.h src/editor/modebar.h \
 src/editor/selbar.h src/editor/modemgr.h src/editor/modes.h src/map.h
$(OBJDIR)/edselect.o: src/editor/edselect.c src/ug/ug.h src/ug/uginter.h \
 src/alloc.h src/editor/edselect.h src/magic/magic4x4.h \
 src/editor/rect.h
$(OBJDIR)/mdlights.o: src/editor/mdlights.c src/alloc.h src/editor/depths.h \
 src/editor/editor.h src/editor/editarea.h src/editor/edselect.h \
 src/ug/ug.h src/list.h src/loaddata.h src/magic/magic4x4.h src/map.h \
 src/editor/modemgr.h src/editor/modes.h src/path.h src/editor/rect.h \
 src/render.h src/editor/selbar.h src/store/store.h src/vtree.h
$(OBJDIR)/mdobject.o: src/editor/mdobject.c src/gui/gui.h src/ug/ug.h \
 src/alloc.h src/editor/cursor.h src/editor/depths.h \
 src/editor/editor.h src/editor/editarea.h src/editor/edselect.h \
 src/list.h src/map.h src/editor/modemgr.h src/editor/modes.h \
 src/editor/selbar.h src/store/store.h src/object.h src/mylua.h \
 src/objtypes.h src/editor/rect.h
$(OBJDIR)/mdstarts.o: src/editor/mdstarts.c src/editor/depths.h \
 src/editor/editor.h src/editor/editarea.h src/editor/edselect.h \
 src/ug/ug.h src/list.h src/magic/magic4x4.h src/map.h \
 src/editor/modes.h src/editor/modemgr.h src/path.h \
 src/editor/selbar.h src/editor/rect.h
$(OBJDIR)/mdtiles.o: src/editor/mdtiles.c src/alloc.h src/editor/depths.h \
 src/editor/editor.h src/editor/editarea.h src/editor/edselect.h \
 src/ug/ug.h src/list.h src/loaddata.h src/magic/magic4x4.h src/map.h \
 src/editor/modemgr.h src/editor/modes.h src/editor/selbar.h \
 src/store/store.h src/vtree.h
$(OBJDIR)/menu.o: src/editor/menu.c src/gui/gui.h src/ug/ug.h \
 src/editor/editarea.h src/editor/editor.h src/map.h src/mapfile.h
$(OBJDIR)/modemgr.o: src/editor/modemgr.c src/gui/gui.h src/ug/ug.h \
 src/editor/modemgr.h
$(OBJDIR)/selbar.o: src/editor/selbar.c src/gui/gui.h src/ug/ug.h \
 src/editor/edselect.h src/editor/selbar.h
