$(OBJDIR)/alloc.o: src/alloc.c src/alloc.h src/error.h
$(OBJDIR)/bindings.o: src/bindings.c src/bindings.h src/mylua.h \
 lua-4.1-work3/include/lua.h lua-4.1-work3/include/lauxlib.h \
 src/client.h src/explo.h src/extdata.h src/loaddata.h \
 src/server/svgame.h src/store/store.h src/object.h src/objtypes.h \
 src/bindings.inc
$(OBJDIR)/bitmask.o: src/bitmask.c src/bitmask.h
$(OBJDIR)/bitmaskg.o: src/bitmaskg.c src/bitmask.h src/bitmaskg.h \
 src/store/store.h
$(OBJDIR)/bitmaskr.o: src/bitmaskr.c src/alloc.h src/bitmask.h src/bitmaskr.h \
 src/list.h
$(OBJDIR)/blod.o: src/blod.c src/blod.h src/map.h src/mylua.h \
 lua-4.1-work3/include/lua.h lua-4.1-work3/include/lauxlib.h \
 src/object.h src/objtypes.h
$(OBJDIR)/camera.o: src/camera.c src/alloc.h src/camera.h \
 src/fastsqrt/fastsqrt.h src/object.h src/mylua.h \
 lua-4.1-work3/include/lua.h lua-4.1-work3/include/lauxlib.h
$(OBJDIR)/client.o: src/client.c libnet/include/libnet.h src/blod.h src/camera.h \
 src/client.h src/error.h src/fps.h src/list.h src/magic/magic4x4.h \
 src/map.h src/mapfile.h src/messages.h src/mylibnet.h src/netmsg.h \
 src/object.h src/mylua.h lua-4.1-work3/include/lua.h \
 lua-4.1-work3/include/lauxlib.h src/packet.h src/particle.h \
 src/render.h src/store/store.h src/sync.h src/timeout.h src/timeval.h
$(OBJDIR)/error.o: src/error.c src/error.h
$(OBJDIR)/explo.o: src/explo.c src/alloc.h src/explo.h src/list.h \
 src/magic/magic4x4.h src/store/store.h
$(OBJDIR)/extdata.o: src/extdata.c src/bitmask.h src/bitmaskg.h src/extdata.h \
 src/magic/magic4x4.h
$(OBJDIR)/fps.o: src/fps.c src/fps.h
$(OBJDIR)/gameinit.o: src/gameinit.c libnet/include/libnet.h src/bindings.h \
 src/bitmaskr.h src/blod.h src/explo.h src/extdata.h \
 src/fastsqrt/fastsqrt.h src/gameinit.h src/jpgalleg/jpgalleg.h \
 src/loaddata.h src/magic/magic4x4.h src/mylua.h \
 lua-4.1-work3/include/lua.h lua-4.1-work3/include/lauxlib.h \
 src/object.h src/objtypes.h src/path.h src/store/store.h
$(OBJDIR)/getoptc.o: src/getoptc.c
$(OBJDIR)/loaddata.o: src/loaddata.c src/alloc.h src/extdata.h src/list.h \
 src/loaddata.h src/path.h src/store/store.h
$(OBJDIR)/main.o: src/main.c libnet/include/libnet.h src/client.h \
 src/editor/editor.h src/gameinit.h src/getoptc.h src/server/server.h \
 src/sync.h src/server/textface.h
$(OBJDIR)/map.o: src/map.c src/alloc.h src/bitmask.h src/explo.h src/list.h \
 src/map.h src/object.h src/mylua.h lua-4.1-work3/include/lua.h \
 lua-4.1-work3/include/lauxlib.h src/particle.h src/store/store.h
$(OBJDIR)/mapfile.o: src/mapfile.c src/list.h src/map.h src/mapfile.h \
 src/object.h src/mylua.h lua-4.1-work3/include/lua.h \
 lua-4.1-work3/include/lauxlib.h src/objtypes.h src/store/store.h
$(OBJDIR)/messages.o: src/messages.c src/client.h src/magic/magic4x4.h \
 src/messages.h src/store/store.h src/timeout.h src/timeval.h
$(OBJDIR)/mylibnet.o: src/mylibnet.c libnet/include/libnet.h src/netmsg.h \
 src/packet.h
$(OBJDIR)/mylua.o: src/mylua.c lua-4.1-work3/include/lua.h \
 lua-4.1-work3/include/lualib.h src/mylua.h \
 lua-4.1-work3/include/lauxlib.h src/path.h
$(OBJDIR)/object.o: src/object.c src/alloc.h src/bitmask.h src/bitmaskg.h \
 src/bitmaskr.h src/list.h src/magic/magic4x4.h src/map.h src/mylua.h \
 lua-4.1-work3/include/lua.h lua-4.1-work3/include/lauxlib.h \
 src/object.h src/objtypes.h src/store/store.h src/objectet.inc
$(OBJDIR)/objtypes.o: src/objtypes.c src/alloc.h src/bitmask.h src/bitmaskg.h \
 src/error.h src/mylua.h lua-4.1-work3/include/lua.h \
 lua-4.1-work3/include/lauxlib.h src/objtypes.h src/store/store.h
$(OBJDIR)/packet.o: src/packet.c src/packet.h src/error.h
$(OBJDIR)/particle.o: src/particle.c src/alloc.h src/bitmask.h src/map.h \
 src/particle.h
$(OBJDIR)/path.o: src/path.c src/path.h
$(OBJDIR)/render.o: src/render.c src/camera.h src/explo.h src/list.h \
 src/magic/magic4x4.h src/map.h src/object.h src/mylua.h \
 lua-4.1-work3/include/lua.h lua-4.1-work3/include/lauxlib.h \
 src/particle.h src/store/store.h src/render.h
$(OBJDIR)/sync.o: src/sync.c src/sync.h src/yield.h
$(OBJDIR)/timeout.o: src/timeout.c src/alloc.h src/timeout.h src/timeval.h
$(OBJDIR)/timeval.o: src/timeval.c src/timeval.h
$(OBJDIR)/yield.o: src/yield.c src/yield.h
$(OBJDIR)/example.o: src/store/example.c src/store/store.h
$(OBJDIR)/hash.o: src/store/hash.c src/store/hash.h
$(OBJDIR)/store.o: src/store/store.c src/store/hash.h src/store/store.h
$(OBJDIR)/magic4x4.o: src/magic/magic4x4.c src/magic/magic4x4.h
$(OBJDIR)/magichf.o: src/magic/magichf.c
$(OBJDIR)/magicrot.o: src/magic/magicrot.c src/magic/magicrot.inc
$(OBJDIR)/bmark.o: src/fastsqrt/bmark.c src/fastsqrt/fastsqrt.h
$(OBJDIR)/fastsqrt.o: src/fastsqrt/fastsqrt.c src/fastsqrt/fastsqrt.h
$(OBJDIR)/jpeg.o: src/jpgalleg/jpeg.c
$(OBJDIR)/gui.o: src/gui/gui.c src/gui/gui.h src/gui/guiinter.h src/yield.h
$(OBJDIR)/guiaccel.o: src/gui/guiaccel.c src/gui/gui.h src/gui/guiinter.h
$(OBJDIR)/guidirty.o: src/gui/guidirty.c src/gui/gui.h src/gui/guiinter.h
$(OBJDIR)/guimouse.o: src/gui/guimouse.c src/gui/gui.h src/gui/guiinter.h
$(OBJDIR)/guiwm.o: src/gui/guiwm.c src/gui/gui.h src/gui/guiinter.h
$(OBJDIR)/guiwmdef.o: src/gui/guiwmdef.c src/gui/gui.h src/gui/guiinter.h
$(OBJDIR)/ug.o: src/ug/ug.c src/ug/ug.h src/ug/ugtheme.h
$(OBJDIR)/ugblank.o: src/ug/ugblank.c src/ug/ug.h src/ug/uginter.h
$(OBJDIR)/ugbutton.o: src/ug/ugbutton.c src/ug/ug.h src/ug/uginter.h \
 src/ug/ugtheme.h
$(OBJDIR)/ugdialog.o: src/ug/ugdialog.c src/gui/gui.h src/ug/ug.h \
 src/ug/uginter.h src/ug/ugtheme.h
$(OBJDIR)/ugevent.o: src/ug/ugevent.c src/ug/ug.h src/ug/uginter.h
$(OBJDIR)/uglayout.o: src/ug/uglayout.c src/ug/ug.h
$(OBJDIR)/ugmenu.o: src/ug/ugmenu.c src/gui/gui.h src/ug/ug.h src/ug/uginter.h \
 src/ug/ugtheme.h
$(OBJDIR)/ugscroll.o: src/ug/ugscroll.c
$(OBJDIR)/ugtheme.o: src/ug/ugtheme.c src/ug/ugtheme.h
$(OBJDIR)/ugthmmot.o: src/ug/ugthmmot.c src/ug/ugtheme.h
$(OBJDIR)/ugthmpaw.o: src/ug/ugthmpaw.c src/ug/ugtheme.h
$(OBJDIR)/ugwidget.o: src/ug/ugwidget.c src/ug/ug.h src/ug/uginter.h
$(OBJDIR)/cursor.o: src/editor/cursor.c src/editor/cursor.h src/magic/magic4x4.h
$(OBJDIR)/editarea.o: src/editor/editarea.c src/gui/gui.h src/alloc.h \
 src/editor/editarea.h src/list.h src/magic/magic4x4.h \
 src/editor/modes.h src/editor/selbar.h
$(OBJDIR)/editor.o: src/editor/editor.c src/gui/gui.h src/ug/ug.h \
 src/editor/cursor.h src/mylua.h lua-4.1-work3/include/lua.h \
 lua-4.1-work3/include/lauxlib.h src/store/store.h src/path.h \
 src/editor/editarea.h src/editor/menu.h src/editor/modebar.h \
 src/editor/selbar.h src/editor/modemgr.h src/editor/modes.h src/map.h
$(OBJDIR)/edselect.o: src/editor/edselect.c src/ug/ug.h src/ug/uginter.h \
 src/alloc.h src/editor/edselect.h src/magic/magic4x4.h \
 src/editor/rect.h
$(OBJDIR)/mdlights.o: src/editor/mdlights.c src/alloc.h src/editor/depths.h \
 src/editor/editor.h src/editor/editarea.h src/editor/edselect.h \
 src/ug/ug.h src/list.h src/loaddata.h src/magic/magic4x4.h src/map.h \
 src/editor/modemgr.h src/editor/modes.h src/path.h src/editor/rect.h \
 src/render.h src/editor/selbar.h src/store/store.h
$(OBJDIR)/mdobject.o: src/editor/mdobject.c src/gui/gui.h src/ug/ug.h \
 src/alloc.h src/editor/cursor.h src/editor/depths.h \
 src/editor/editor.h src/editor/editarea.h src/editor/edselect.h \
 src/list.h src/map.h src/editor/modemgr.h src/editor/modes.h \
 src/editor/selbar.h src/store/store.h src/object.h src/mylua.h \
 lua-4.1-work3/include/lua.h lua-4.1-work3/include/lauxlib.h \
 src/objtypes.h src/editor/rect.h
$(OBJDIR)/mdstarts.o: src/editor/mdstarts.c src/editor/depths.h \
 src/editor/editor.h src/editor/editarea.h src/editor/edselect.h \
 src/ug/ug.h src/list.h src/magic/magic4x4.h src/map.h \
 src/editor/modes.h src/editor/modemgr.h src/path.h \
 src/editor/selbar.h src/store/store.h src/editor/rect.h
$(OBJDIR)/mdtiles.o: src/editor/mdtiles.c src/alloc.h src/editor/depths.h \
 src/editor/editor.h src/editor/editarea.h src/editor/edselect.h \
 src/ug/ug.h src/list.h src/loaddata.h src/magic/magic4x4.h src/map.h \
 src/editor/modemgr.h src/editor/modes.h src/editor/selbar.h \
 src/store/store.h
$(OBJDIR)/menu.o: src/editor/menu.c src/gui/gui.h src/ug/ug.h \
 src/editor/editarea.h src/editor/editor.h src/map.h src/mapfile.h
$(OBJDIR)/modemgr.o: src/editor/modemgr.c src/gui/gui.h src/ug/ug.h \
 src/editor/modemgr.h
$(OBJDIR)/selbar.o: src/editor/selbar.c src/gui/gui.h src/ug/ug.h \
 src/editor/edselect.h src/editor/selbar.h
$(OBJDIR)/server.o: src/server/server.c libnet/include/libnet.h src/error.h \
 src/list.h src/netmsg.h src/object.h src/mylua.h \
 lua-4.1-work3/include/lua.h lua-4.1-work3/include/lauxlib.h \
 src/packet.h src/server/server.h src/server/svclient.h src/timeout.h \
 src/timeval.h src/server/svgame.h src/server/svintern.h \
 src/server/svlobby.h src/sync.h
$(OBJDIR)/svclient.o: src/server/svclient.c libnet/include/libnet.h src/alloc.h \
 src/list.h src/netmsg.h src/packet.h src/server/server.h \
 src/server/svclient.h src/timeout.h src/timeval.h src/server/svgame.h \
 src/server/svintern.h src/server/svstats.h
$(OBJDIR)/svgame.o: src/server/svgame.c src/alloc.h src/error.h src/list.h \
 src/map.h src/mapfile.h src/netmsg.h src/object.h src/mylua.h \
 lua-4.1-work3/include/lua.h lua-4.1-work3/include/lauxlib.h \
 src/objtypes.h src/packet.h src/sync.h src/server/server.h \
 src/server/svclient.h src/timeout.h src/timeval.h \
 src/server/svintern.h src/server/svstats.h src/server/svticker.h
$(OBJDIR)/svlobby.o: src/server/svlobby.c src/netmsg.h src/server/server.h \
 src/server/svclient.h src/timeout.h src/timeval.h \
 src/server/svintern.h
$(OBJDIR)/svstats.o: src/server/svstats.c src/timeval.h
$(OBJDIR)/svticker.o: src/server/svticker.c src/alloc.h src/server/svticker.h \
 src/timeval.h
$(OBJDIR)/textface.o: src/server/textface.c src/server/server.h \
 src/server/svintern.h src/server/textface.h
