#include <stdio.h>

int main(void)
{
	printf(
		"# GCC command line configuration, generated by gccver.c\n"
#if __GNUC__ >= 3
		"# GCC Version 3.x: all is dandy!\n"
		"WFLAGS := -Wall -W -Wwrite-strings -Wno-system-headers -Wmissing-declarations\n"
		"WFLAGS_ALLEGRO :=\n"
#else
		"# GCC Version 2.x: -Wno-system-headers and attribute((deprecated)) don't exist!\n"
		"# IMPORTANT: see release.txt before using -DDUMB_DECLARE_DEPRECATED yourself!\n"
		"WFLAGS := -Wall -W -Wwrite-strings -Wmissing-declarations -DDUMB_DECLARE_DEPRECATED\n"
		"WFLAGS_ALLEGRO := -Wno-missing-declarations\n"
#endif
	);
	return 0;
}
