/* scripts/_imports.sh: automatically generated by 		-*- mode: C -*- */
/* autoexp on Tue May 11 12:09:20 1999 */
/* Do not edit ! */

/* src/defs.h */
typedef unsigned int msg_t;	       
typedef int seer_addr;		       

/* src/mapedit.h */
import        BITMAP *dbuf;		       

/* src/script.h */
import int addressof(char *symbol);	       		
import int exec_script(char *filename, char *func);	
import int add_script(char *filename);	       		

/* src/tiles.h */
import void create_tiles_table(int size);     
import void add_tiles_pack(char *filename);   

/* src/wrapper.h */
import DATAFILE *df_get_item(DATAFILE *dat, char *name);   	
import DATAFILE *df_item(DATAFILE *dat, unsigned int i);   	
import void *df_dat(DATAFILE *d);	       			
import int df_count(DATAFILE *dat, int type); 			
import int df_foreach(DATAFILE *dat, int (*callback)(DATAFILE *d));
import unsigned char *bmp_line(BITMAP *bmp, unsigned int row);	
import int bmp_w(BITMAP *b);		
import int bmp_h(BITMAP *b);
import        int printf (char* format, ...); 

/* src/object.h */
typedef void object_def_t;
typedef void object_t;
import int create_object_type(char *name, int handler, BITMAP *icon);	

/* src/player.h */

struct player_t {
unsigned int x, y;
};

/* src/weapon.h */
typedef void (*weapon_handler_t)(msg_t msg, player_t *pl);   
typedef void (*object_handler_t)(msg_t msg, object_t *obj, player_t *pl);
typedef void weapon_type_t;	       
import int create_weapon_type(char *name);    
import int assign_weapon_handler(int typenum, seer_addr handler);
