/* scripts/_imports.sh: automatically generated by 		-*- mode: C -*- */
/* autoexp on Sun Apr 25 21:24:59 1999 */
/* Do not edit ! */

/* src/defs.h */
typedef unsigned int msg_t;	       

/* src/mapedit.h */
import        BITMAP *dbuf;		       

/* src/script.h */
import int exec_script(char *filename, char *func);   	
import int add_script(char *filename);	       		

/* src/tiles.h */
import void create_tiles_table(int size);     
import void add_tiles_pack(char *filename);   

/* src/wrapper.h */
import DATAFILE *df_get_item(DATAFILE *dat, char *name);   	
import DATAFILE *df_item(DATAFILE *dat, unsigned int i);   	
import void *df_dat(DATAFILE *d);	       			
import int df_count(DATAFILE *dat, int type); 			
import int df_foreach(DATAFILE *dat, int (*callback)(DATAFILE *d));
import unsigned char *bmp_line(BITMAP *bmp, unsigned int row);	
import int bmp_w(BITMAP *b);		
import int bmp_h(BITMAP *b);	

/* src/object.h */

struct object_def_t {
};

struct object_t {
unsigned int x, y;
};
