/* src/_export.c: automatically generated by 		-*- mode: C -*- */
/* autoexp on Sun Apr 25 21:24:59 1999 */
/* Do not edit ! */

/* src/defs.h */
scAddExtSym(msg_t);

/* src/mapedit.h */
scAddExtSym(dbuf);

/* src/script.h */
scAddExtSym(exec_script);
scAddExtSym(add_script);

/* src/tiles.h */
scAddExtSym(create_tiles_table);
scAddExtSym(add_tiles_pack);

/* src/wrapper.h */
scAddExtSym(df_get_item);
scAddExtSym(df_item);
scAddExtSym(df_dat);
scAddExtSym(df_count);
scAddExtSym(df_foreach);
scAddExtSym(bmp_line);
scAddExtSym(bmp_w);
scAddExtSym(bmp_h);

/* src/object.h */

struct object_def_t {
};

struct object_t {
scAddExtSym(x);
};
