/* src/_export.c: automatically generated by 		-*- mode: C -*- */
/* autoexp on Wed May 26 23:38:23 1999 */
/* Do not edit ! */

/* src/defs.h */

/* src/mapedit.h */
scAddExtSym(dbuf);

/* src/script.h */
scAddExtSym(addressof);
scAddExtSym(exec_script);
scAddExtSym(add_script);

/* src/tiles.h */
scAddExtSym(add_tiles_pack);

/* src/wrapper.h */
scAddExtSym(df_get_item_num);
scAddExtSym(df_get_item);
scAddExtSym(df_item);
scAddExtSym(df_dat);
scAddExtSym(df_count);
scAddExtSym(df_foreach);
scAddExtSym(bmp_line);
scAddExtSym(bmp_w);
scAddExtSym(bmp_h);
scAddExtSym(printf);

/* src/object.h */
scAddExtSym(create_object_type);

/* src/weapon.h */
scAddExtSym(create_weapon_type);
scAddExtSym(assign_weapon_handler);
